import{S as f,i as d}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();function m(s){const{hits:r}=s,n=document.querySelector(".photos-list"),o=r.map(({downloads:t,comments:a,views:l,likes:u,tags:p,webformatURL:A,largeImageURL:h})=>`
    <li class="gallery">
      <a class="gallery-link" href="${h}"><img src="${A}" alt="${p}" loading="lazy">
      <div class="gallery-wrap"><span class="span">Likes <span class="value">${u}</span></span>
      <span class="span">Views <span class="value">${l}</span></span>
      <span class="span">Comments <span class="value">${a}</span></span>
      <span class="span">Downloads <span class="value">${t}</span></span></div></a>
    </li>`).join("");c(),n.insertAdjacentHTML("beforeend",o),new f(".gallery a").refresh()}function c(){const s=document.querySelector(".photos-list");return s.innerHTML=""}const g="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEaSURBVHgBrZZhDoIwDIUL0fjXo3gUb7R5Er0BHsXD7A+bASlhYeC6V4WXGCHr3reNtkAkqG2D9T70mh/HSj4HybyqyPQ9PeuaXlRQ19GFY4c5dDodLSHNK3/fSam29Q+0k7/N1ZAt5hCyh7kIKZl77y/IMBezgEwXTW4ienBxcc65DCQ0PDYCQghGMDASJJpzTG4ue0KABEHmKeBAQEPx3LiIhmKy/M+aitDyGJoPAWsI32vNWTXpVQnXRal2kPQmO7pPx6XpPRCQmsdjSZ8JhIA0FbOllMKsRZqCQoMpXCy0GJRrFc7hVpGLSVqFWaxk52ZnVgPbIaL5HhBovgVSMv+qg7kt9JznZ+VL//pL+5hWFXei+mwRj+UDSHQ9vnHBEYAAAAAASUVORK5CYII=";function y(s){const r="44930216-c8fe7065044399c3ab26c911d",n="https://pixabay.com/api/",o=new URLSearchParams({q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"});return fetch(`${n}?key=${r}&${o}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{if(e.hits.length===0){c(),d.error({position:"topRight",title:"Sorry,",message:"there are no images matching your search query. Please try again!",titleColor:"white",titleSize:"16px",messageColor:"white",backgroundColor:"#ef4040",iconUrl:g,layout:2});return}return e}).catch(e=>console.error(e))}const i={form:document.querySelector(".js-form"),spinner:document.querySelector(".js-loader")};i.form.addEventListener("submit",L);function L(s){s.preventDefault();const r={};if(new FormData(s.target).forEach((n,o)=>r[o]=n.trim().toLowerCase()),!r.textValue){alert("it is empty");return}i.spinner.hidden=!1,y(r.textValue).then(n=>m(n)).finally(()=>{i.spinner.hidden=!0}),s.currentTarget.reset()}
//# sourceMappingURL=commonHelpers.js.map
