import{i as u}from"./assets/vendor-8e8cd629.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();function f(o){const{hits:r}=o,n=document.querySelector(".photos-list"),s=r.map(({downloads:e,comments:t,views:i,likes:a,tags:c,webformatURL:l})=>`
    <li>
      <img src="${l}" alt="${c}" loading="lazy">
      <span>Likes ${a}</span>
      <span>Views ${i}</span>
      <span>Comments ${t}</span>
      <span>Downloads ${e}</span>
    </li>`).join("");n.innerHTML="",n.insertAdjacentHTML("beforeend",s),$(".photos-list a").simpleLightbox()}function m(o){const r="44930216-c8fe7065044399c3ab26c911d",n="https://pixabay.com/api/",s=new URLSearchParams({q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"});return fetch(`${n}?key=${r}&${s}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).then(e=>{if(e.hits.length===0){u.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}console.log(e),console.log(f(e))}).catch(e=>console.error(e))}const d={form:document.querySelector(".form")};d.form.addEventListener("submit",p);function p(o){o.preventDefault();const r={};if(new FormData(o.target).forEach((n,s)=>r[s]=n.trim().toLowerCase()),!r.textValue){alert("it is empty");return}m(r.textValue),o.currentTarget.reset()}
//# sourceMappingURL=commonHelpers.js.map
